name: CI Pipeline

on:
  push:
    branches:
      - main
      - user-service
  pull_request:
    branches:
      - main
      - user-service

jobs:
  build-test-sonarqube-docker:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: marketplace
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      SPRING_PROFILES_ACTIVE: docker
      POSTGRES_URL: jdbc:postgresql://postgres:5432/marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Wait for Postgres and Redis
        run: |
          until pg_isready -h postgres -U postgres; do sleep 1; done
          until redis-cli -h redis ping | grep PONG; do sleep 1; done

      - name: Run tests
        run: mvn test

      - name: SonarQube analysis
        run: mvn sonar:sonar \
          -Dsonar.projectKey=oldvabik_marketplace \
          -Dsonar.organization=oldvabik \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t marketplace-app .
          docker save marketplace-app -o marketplace-app.tar

      - name: Save Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: marketplace-docker-image
          path: ./marketplace-app.tar
